version: 1.0.{build}
configuration: Release
before_build:
- cmd: >-
    dotnet restore

    dotnet build
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: Marco.ExceptionHandling
- path: '**\*.nupkg'
  name: Marco.ExceptionHandling.Abstractions
deploy:
- provider: NuGet
  api_key:
    secure: uXr+x5ThtyLuhAJw9mbQSMHez0jozItL+yH7Mqnv1cz+KRfwbNkaAAZX/0aPIjJy
- provider: NuGet
  api_key:
    secure: B4moTSnYcslKTy4E9psGJvANYyoDuq4NBVLNWgyqc/iPLjkOVgS7+GTW7UOfNCsV