version: 1.0.{build}
configuration: Release
before_build:
- cmd: >-
    dotnet restore

    dotnet build
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: Marco.ExceptionHandling
- path: '**\*.nupkg'
  name: Marco.ExceptionHandling.Abstractions
deploy:
- provider: NuGet
  api_key:
    secure: +/HtiqBX2E5C1Zcjsh2OkjVnUYYA1UItEQpIDXtbRJpP27f3xz+57/5MCLVVCk/9
- provider: NuGet
  api_key:
    secure: NpBy2beIpnCBNCSnBx2kiaDXMq7olm0XEIlbdHwSu574v54l4jvKEZubrcIgxKf7
