version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
before_build:
- cmd: >-
    dotnet restore

    dotnet build
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: Marco.ExceptionHandling
deploy:
- provider: NuGet
  api_key:
    secure: RCtjjLPpGMVjt4mD8LurHJ9fhXCmpZwOH6HKXTh34VoN2sjJUvX56WrHzv8OA6MG
